name: Build et Release

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculer la prochaine version
        id: version
        run: |
          # Récupérer la dernière version ou utiliser v0.1.0 si aucune n'existe
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          echo "Dernière version: $LATEST_TAG"
          
          # Extraire les composants de version
          VERSION=${LATEST_TAG#v}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          
          # Récupérer le dernier message de commit
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Déterminer quel niveau de version doit être incrémenté
          if echo "$COMMIT_MSG" | grep -q "\[bump-major\]"; then
            echo "Incrémentation de la version majeure détectée dans le message de commit"
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif echo "$COMMIT_MSG" | grep -q "\[bump-minor\]"; then
            echo "Incrémentation de la version mineure détectée dans le message de commit"
            MINOR=$((MINOR + 1))
            PATCH=0
          elif echo "$COMMIT_MSG" | grep -q "\[version="; then
            # Format personnalisé: [version=X.Y.Z]
            CUSTOM_VERSION=$(echo "$COMMIT_MSG" | grep -o '\[version=[0-9]*\.[0-9]*\.[0-9]*\]' | sed 's/\[version=\(.*\)\]/\1/')
            if [ ! -z "$CUSTOM_VERSION" ]; then
              echo "Version personnalisée détectée: $CUSTOM_VERSION"
              MAJOR=$(echo $CUSTOM_VERSION | cut -d. -f1)
              MINOR=$(echo $CUSTOM_VERSION | cut -d. -f2)
              PATCH=$(echo $CUSTOM_VERSION | cut -d. -f3)
            else
              # Incrémentation de patch par défaut
              PATCH=$((PATCH + 1))
            fi
          else
            # Incrémentation de patch par défaut
            PATCH=$((PATCH + 1))
          fi
          
          # Nouvelle version
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "Nouvelle version: $NEW_VERSION"
          echo "tag=$NEW_VERSION" >> $GITHUB_OUTPUT

  build-binary:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Installer cross
        run: cargo install cross

      - name: Créer Cross.toml pour spécifier OpenSSL vendored
        run: |
          cat > Cross.toml << 'EOF'
          [build.env]
          passthrough = [
            "RUSTFLAGS",
            "OPENSSL_STATIC",
            "OPENSSL_NO_VENDOR"
          ]
          EOF

      - name: Construire avec cross et OpenSSL vendored
        env:
          OPENSSL_STATIC: 1
          RUSTFLAGS: "-C target-feature=+crt-static"
          OPENSSL_NO_VENDOR: 0
        run: |
          cross build --release --target x86_64-unknown-linux-musl --features vendored-openssl

      - name: Préparer le binaire
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-musl/release/github-ntfy release/github-ntfy

      - name: Upload binaire comme artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-ntfy
          path: release/github-ntfy

  build-frontend:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '10.x'
          run_install: false

      - name: Build Frontend (Nuxt)
        run: |
          cd web
          pnpm install
          pnpm generate

      - name: Vérifier le contenu du répertoire output
        run: |
          ls -la web/.output/public || echo "Le répertoire .output n'existe pas!"

      - name: Upload frontend comme artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-frontend
          path: web/.output/public

  docker-build-push:
    needs: [version, build-binary, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Télécharger le binaire
        uses: actions/download-artifact@v4
        with:
          name: github-ntfy
          path: binaries

      - name: Télécharger le frontend
        uses: actions/download-artifact@v4
        with:
          name: nuxt-frontend
          path: web/.output/public

      - name: Préparer les fichiers pour Docker
        run: |
          chmod +x binaries/github-ntfy
          mkdir -p docker-build
          cp binaries/github-ntfy docker-build/
          mkdir -p docker-build/web-output/public
          cp -r web/.output/public/* docker-build/web-output/public/
          cp nginx.conf docker-build/
          cp entrypoint.sh docker-build/
          cp Dockerfile docker-build/
          chmod +x docker-build/entrypoint.sh

      - name: Construire et pousser l'image Docker
        uses: docker/build-push-action@v6
        with:
          context: docker-build
          push: true
          tags: |
            breizhhardware/github-ntfy:latest
            breizhhardware/github-ntfy:${{ needs.version.outputs.version }}
          file: docker-build/Dockerfile

  create-release:
    needs: [version, build-binary, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Télécharger le binaire
        uses: actions/download-artifact@v4
        with:
          name: github-ntfy
          path: binaries

      - name: Télécharger le frontend
        uses: actions/download-artifact@v4
        with:
          name: nuxt-frontend
          path: web/.output/public

      - name: Préparer les fichiers pour la release
        run: |
          mkdir -p release-artifacts
          cp binaries/github-ntfy release-artifacts/
          tar -czf release-artifacts/frontend.tar.gz -C web/.output/public .

      - name: Créer une release GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.version.outputs.version }}
          name: Release ${{ needs.version.outputs.version }}
          files: |
            release-artifacts/github-ntfy
            release-artifacts/frontend.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}