name: Dependabot Build Check

on:
  pull_request:
    branches: [dev]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    if: ${{ startsWith(github.head_ref, 'dependabot/') || github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Installer cross
        run: cargo install cross

      - name: Créer Cross.toml pour spécifier OpenSSL vendored
        run: |
          cat > Cross.toml << 'EOL'
          [target.x86_64-unknown-linux-musl]
          image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

          [build.env]
          passthrough = [
              "RUST_BACKTRACE",
          ]
          EOL

      - name: Build Backend (Rust)
        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '10.x'
          run_install: false

      - name: Build Frontend (Nuxt)
        run: |
          cd web
          pnpm install
          pnpm build

      - name: Afficher des informations de débogage
        run: |
          echo "Acteur: ${{ github.actor }}"
          echo "Référence de la branche: ${{ github.head_ref }}"
          echo "Event name: ${{ github.event_name }}"